fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "fosub@localhost"
        sender_name: FOSUB
    use_flash_notifications: false

